### ISSUE TITLE
Require the CodeMirror mips mode directly in main.js

### ISSUE THREAD

**Issue by petetnt** [naphipps/brackets-mips-syntax-highlighter#1]
Hi Nathan!

Continuing a bit from https://groups.google.com/forum/#!topic/brackets-dev/AEXT7hdu2s0

First a question: Does the installer do anything else except copy the [mode/mips/mips.js](https://github.com/naphipps/brackets-mips-syntax-highlighter/blob/master/mode/mips/mips.js) file to the correct place? 

Regardless of that, you can just use `require` in your `main.js` to require the CodeMirror mode file:

```
define(function (require, exports, module) {
  "use strict";
  var LanguageManager = brackets.getModule("language/LanguageManager");
  
  require("./mode/mips/mips");

  LanguageManager.defineLanguage("mips", { 
    name: "mips",
    mode: "mips",
    fileExtensions: ["s","sx"],
    lineComment: ["#"]
  });
});
```

Now the `mips`-mode is automatically defined to anyone who installs your extension. Just make sure that the `mode/mips` folder is included in the `.zip`

**Comment by naphipps** [comment]
Hey Pete!

Answer to question: Nope. The installer just copies the mode to the right spot.

Thanks! I didn't know I could add the require. Let me try that, because the ```mode/mips folder``` is included in the ```.zip```

**Comment by naphipps** [comment]
Aha! I defined the CodeMirror mips mode inside the ```main.js``` so I won't have to use the ```require```. Plus, this way, I only have to worry about the ```main.js``` and ```package.json``` in the ```.zip```.

(Using the ```require``` didn't seem to be working for me, although, I may have been approaching it the wrong way.)

Nevertheless, I'll have this quick fix up in no time!

Thanks again Pete, for your insight!

**Comment by petetnt** [comment]
Yup, that works too. 

Weird though, `require("./mode/mips/mips")` should have worked though: when loaded, it should have just called the `CodeMirror.defineMode`-method. But like you said, doing it all in the `main.js` file works too :+1:
